import {
  HttpEvent,
  HttpHandler,
  HttpInterceptor,
  HttpRequest,
} from '@angular/common/http';
import { Injectable } from '@angular/core';

import { Observable } from 'rxjs';
import { StateService } from '../services/state.services';

@Injectable()
export class GraphqlHeaderInterceptor implements HttpInterceptor {
  constructor(private stateservice:StateService) {}
  intercept(
    request: HttpRequest<unknown>,
    next: HttpHandler
  ): Observable<HttpEvent<unknown>> {
    let customRequest = request;
    customRequest = request.clone({
      setHeaders: {
        // Authorization: `Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IlYydXpRaHVmYmNMRUw0U0VtZklyVWhXVm1paEhYTS0zSHREd0oyVVNBdnciLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8xNGY3M2FlZi1lMDQxLTQ5NWMtOTUzMy01YzhmNWZlMTJiMjYvIiwiaWF0IjoxNjc3MzQ3MDE4LCJuYmYiOjE2NzczNDcwMTgsImV4cCI6MTY3NzM1MjU5MSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFZUUFlLzhUQUFBQTlBK3FUUTF6enhPR2c0bUFET2NKTStwaTlCSXlIUzBIMCticm1sKzk3cFZGaWowYStQeFRRZDVCSk9uVWRoV1hNaXBLUTZsRTJna25hcERmVjUwNzRscnF1VnRvSTlxUm5ZN2dXL3hqMTQ1QURnV3JyNGc3SHNtVGU5ckpNMmFERWhzS3pzbW4zenVRamJrM2kyOHdBQ3hhOWVzdVdVWGVHdE1oNUt6cXNUdz0iLCJhbHRzZWNpZCI6IjE6bGl2ZS5jb206MDAwMzdGRkUyQkE5OEVGQiIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiRGlnaXRhbC1TaG9wcGluZyIsImFwcGlkIjoiM2NkMzdiYzgtNzJiNC00OTFkLWIxNTctNjAyNTViYWI3NGU5IiwiYXBwaWRhY3IiOiIwIiwiZW1haWwiOiJuYW5kYWt1bWFyMDY5OEBnbWFpbC5jb20iLCJmYW1pbHlfbmFtZSI6Ikt1bWFyIiwiZ2l2ZW5fbmFtZSI6Ik5hbmRhIiwiaWRwIjoibGl2ZS5jb20iLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNTcuNDUuMTIzLjIxIiwibmFtZSI6Ik5hbmRhIEt1bWFyIiwib2lkIjoiMTRhOGFkZWUtNTE3YS00MzllLTg4NmMtNTcyNGEzN2RkYTA1IiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDAxRTBEM0I4OTUiLCJyaCI6IjAuQVhFQTd6cjNGRUhnWEVtVk0xeVBYLUVySmdNQUFBQUFBQUFBd0FBQUFBQUFBQUNIQUNZLiIsInNjcCI6ImVtYWlsIFVzZXIuUmVhZCBwcm9maWxlIG9wZW5pZCIsInN1YiI6IlZ5SE4wQlNadk1ZLUZIY2hKTHpGWDMxclA4M2RwV2hWaEU0eVh4MlZDOVUiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiQVMiLCJ0aWQiOiIxNGY3M2FlZi1lMDQxLTQ5NWMtOTUzMy01YzhmNWZlMTJiMjYiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI25hbmRha3VtYXIwNjk4QGdtYWlsLmNvbSIsInV0aSI6Im9MTzIzZ1l3bVVxbUtwemMtb013QUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjYyZTkwMzk0LTY5ZjUtNDIzNy05MTkwLTAxMjE3NzE0NWUxMCIsImYwMjNmZDgxLWE2MzctNGI1Ni05NWZkLTc5MWFjMDIyNjAzMyIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfc3QiOnsic3ViIjoiOW9EbjVpcG1tQ19GUG5JY3hFWE9ydDRUY2RTbEJ1MzloZnlMdGJiN3FxSSJ9LCJ4bXNfdGNkdCI6MTY0NjMwMTAxNX0.eGIlBWwMtk8M2OdxTlMJOhZXoBnmO_VsKcqb-HWw4PW9eGXUkIkAWICi-ZNs_7vuad_R8Zo2trdnlKjOohEkuxXwsKe0qZxUT14FAS2LAMoX6cn3QvCQGi8bu3l_kWWM3KEKBGyJgR25E0LhBYj5PBV92AslHJzxT9_O0VCGx5DJRKJYnQYak2F-od4vuVtm9y5gw7L3qcKKMLu10sX7foqZ6xHOwBrPno6obem2Gslwd7brDWQ3uihsHwZxJvARKdVTarx-aIpeWecBuZSjd4obKUCnRSbYeVVWn42tN16VJjxg7aqWoo6RST34iwkRKSWmI_-jeXeJ2Y5sRgEP1Q`,
         Authorization: `Bearer ${this.stateservice.state.accessToken}`,
       // Authorization: `Bearer ${this.cookie.get('tkn')}`,
       
      },
    });
    return next.handle(customRequest);
  }
}
